-- Migration : Ajout des colonnes manquantes pour aligner la structure avec l'application

-- Table rooms
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS type_chambre VARCHAR;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS prix_nuit NUMERIC;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS nom VARCHAR;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS etage INTEGER;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS surface NUMERIC;

-- Table reservations
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS numero VARCHAR;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS type VARCHAR;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS nom VARCHAR;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS capacite INTEGER;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS etage INTEGER;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS surface NUMERIC;

-- Table hotels
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS hotel_id INTEGER;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS numero VARCHAR;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS type VARCHAR;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS prix NUMERIC;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS capacite INTEGER;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS etage INTEGER;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS surface NUMERIC;

-- Table usagers
ALTER TABLE usagers ADD COLUMN IF NOT EXISTS hotel_id INTEGER;
ALTER TABLE usagers ADD COLUMN IF NOT EXISTS numero VARCHAR;
ALTER TABLE usagers ADD COLUMN IF NOT EXISTS type VARCHAR;
ALTER TABLE usagers ADD COLUMN IF NOT EXISTS prix NUMERIC;
ALTER TABLE usagers ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE usagers ADD COLUMN IF NOT EXISTS capacite INTEGER;
ALTER TABLE usagers ADD COLUMN IF NOT EXISTS etage INTEGER;
ALTER TABLE usagers ADD COLUMN IF NOT EXISTS surface NUMERIC;

-- Table operateurs_sociaux
ALTER TABLE operateurs_sociaux ADD COLUMN IF NOT EXISTS hotel_id INTEGER;
ALTER TABLE operateurs_sociaux ADD COLUMN IF NOT EXISTS numero VARCHAR;
ALTER TABLE operateurs_sociaux ADD COLUMN IF NOT EXISTS type VARCHAR;
ALTER TABLE operateurs_sociaux ADD COLUMN IF NOT EXISTS prix NUMERIC;
ALTER TABLE operateurs_sociaux ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE operateurs_sociaux ADD COLUMN IF NOT EXISTS capacite INTEGER;
ALTER TABLE operateurs_sociaux ADD COLUMN IF NOT EXISTS etage INTEGER;
ALTER TABLE operateurs_sociaux ADD COLUMN IF NOT EXISTS surface NUMERIC; 